var _ = getApp(), E = require("./requestlog.js"), e = require("./urls.js"), T = require("./wglogin.js"), N = require("./urlGL.js").HOMEPAGE();

module.exports = {
    EVENT_BSB_ADVERT_EVENTS: "bsb_advert_click",
    EVENT_BSB_SHARE_EVENTS: "bsb_share",
    EVENT_THINKDATATRACK: function(E) {
        var e = getCurrentPages(), T = e[e.length - 1].route;
        E.page_name = N[T], E.page_url = T;
        var i = E;
        _.thinkingdata.track(E.event, i);
    },
    EVENT_SHARE_FLAG: function() {
        return T.USERINFO().userId + "" + Date.parse(new Date()) / 1e3;
    },
    EVENT_COMMUNITY_ENTER_INDEX_POST_DETAILS_CLICK: "enter_index_post_details_click",
    EVENT_COMMUNITY_ENTER_INDEX_TOPICS_CLICK: "enter_index_topics_click",
    EVENT_COMMUNITY_COMMUNITY_TOTAL_TIME: "community_total_time",
    EVENT_COMMUNITY_ENTER_INDEX_POSTING_CLICK: "enter_index_posting_click",
    EVENT_COMMUNITY_ENTER_INDEX_POSTING_STAY_TIME: "enter_index_posting_stay_time",
    EVETN_COMMUNITY_ENTER_INDEX_POSATING_KOIN_IN_TOPICS_CLICK: "enter_index_posting_join_in_topics_click",
    EVENT_COMMUNITY_ENTER_INDEX_POSTING_LOCATION_CLICK: "enter_index_posting_location_click",
    EVENT_COMMUNITY_ENTER_INDEX_POSTING_FINISH_CLICK: "enter_index_posting_finish_click",
    EVENT_COMMUNITY_ENTER_INDEX_RECOMMEND_CLICK: "enter_index_recommend_click",
    EVENT_COMMUNITY_ENTER_INDEX_RECOMMEND_STAY_TIME: "enter_index_recommend_stay_time",
    EVENT_COMMUNITY_ENTER_INDEX_FOLLOW_CLICK: "enter_index_follow_click",
    EVENT_COMMUNITY_ENTER_INDEX_FOLLOW_STAY_TIME: "enter_index_follow_stay_time",
    EVENT_COMMUNITY_ENTER_INDEX_MY_FOLLOW_CLICK: "enter_index_my_follow_click",
    EVENT_COMMUNITY_ENTER_INDEX_MY_FOLLOW_STAY_TIME: "enter_index_my_follow_stay_time",
    EVENT_COMMUNITY_ENTER_INDEX_MY_PAGE_CLICK: "enter_index_my_page_click",
    EVENT_COMMUNITY_MY_PAGE_STAY_TIME: "enter_index_my_page_stay_time",
    EVENT_COMMUNITY_MY_PAGE_FORWARD_CLICK: "my_page_forward_click",
    EVENT_COMMUNITY_MY_PAGE_FORWARD_SHARE: "my_page_forward_share",
    EVENT_COMMUNITY_FRIENDS_FOLLOW_CLICK: "enter_index_friends_follow_click",
    EVENT_COMMUNITY_FRIENDS_FOLLOW_CANCEL: "enter_index_friends_follow_cancel",
    EVENT_HOMEPAGE_CLICK_MESSAGE_BTN: "hompage_click_message_btn",
    EVENT_MONEYTRPAGESTAY: "moneyTreePageStay",
    EVENT_MONEYTREEBTNCLICK: "moneyTree_shake_btnclick",
    EVENT_TEAM_PAGESTAYTIME: "teamPageStayTime",
    EVENT_RECORD_PAGESTAYTIME: "recordPageStayTime",
    EVENT_TEAM_DETAILCLICKMANGERBTN: "teamDetailClickMangerBtn",
    EVENT_TEAM_BANNERCLICK: "teamBannerClick",
    EVENT_TEAM_CREATGROUPCLICK: "teamCreatGroupClick",
    EVENT_INDEX_CLICK_PUSHMESSAGE: "index_click_pushMessage",
    EVENT_ACTIVITY_PRIZED_ALLVEDIO: "activity_prized_allVedio",
    EVENT_ACTIVITY_PRIZED_AGAIN: "activity_prized_again",
    EVENT_INDEXCLICKTOGOTOP: "indexPage_click_gotoTop",
    EVENT_HOTHELPDETAILSHAREBTNCLICK: "hotHelpDetailShareBtnClick",
    EVENT_ANSWERPAGESTAYTIME: "answerPageStayTime",
    EVENT_HOMEPAGEADBUTTON: "homepage_clickAdbutton",
    EVENT_ACTIVEWELFARECLICK: "welfareActiveBtnClick",
    EVENT_ACTIVEHOTHELCLICK: "hotHelpActiveBtnClick",
    EVENT_ACTIVEBTNCLICKOTHERTYPE: "activeBtnClickOtherType",
    EVENT_INDEXANSWERBTNCLICK: "indexAnswerBtnClick",
    EVENT_ANSWERSHAREBTNCLICK: "answerShareBtnClick",
    EVENT_ADDITIONRULESHAREBTN: "additionRuleShareBtn",
    EVENT_WELFARESAVEBTN: "welfareSaveBtn",
    EVENT_WELFARESHAREBTN: "welfareShareBtn",
    EVENT_GOTODAIRYBUTTON: "homePage_gotoDairyButton",
    EVENT_LOG: function(E, N, i) {
        if (T.USERINFO().userId) {
            var a = E;
            if (a.bsb_version = e.APP_VERSION, !_.globalData.setOnce) {
                var t = {};
                _.globalData.userLogindetail.userInfo && (t.gender = _.globalData.userLogindetail.userInfo.gender ? _.globalData.userLogindetail.userInfo.gender : "", 
                t.city = _.globalData.userLogindetail.userInfo.city ? _.globalData.userLogindetail.userInfo.city : "", 
                t.province = _.globalData.userLogindetail.userInfo.province ? _.globalData.userLogindetail.userInfo.province : "", 
                t.country = _.globalData.userLogindetail.userInfo.country ? _.globalData.userLogindetail.userInfo.country : "", 
                _.globalData.userLogindetail.userInfo.createTime && "" != _.globalData.userLogindetail.userInfo.createTime && void 0 != _.globalData.userLogindetail.userInfo.createTime && (t.createTime = _.globalData.userLogindetail.userInfo.createTime)), 
                _.thinkingdata.userSetOnce(t), _.globalData.setOnce = !0;
            }
            "" != _.globalData.loginTime && _.globalData.loginTime && (_.thinkingdata.userSet({
                loginTime: _.globalData.loginTime
            }), _.globalData.loginTime = ""), _.thinkingdata.track(E.event, a);
        }
    },
    EVENT_DATA_LOG: function(_) {
        var N = wx.getStorageSync("system"), i = wx.getStorageSync("network"), a = _;
        a.uid = T.USERINFO().userId + "", a.network = i, a.phone_brand = N.brand, a.phone_model = N.model, 
        a.phone_os = N.platform, a.phone_os_version = N.system, a.wechat_version = N.version, 
        a.font_size = N.fontSizeSetting, _.advertId && (a.commodity_id = _.advertId), E.POST({
            url: e.LOG,
            params: a,
            success: function(_) {},
            fail: function(_) {}
        });
    },
    EVENT_LOG_PERSONINFO: "homePage_dialog_personalInformationAuthorization",
    EVENT_LOG_SPORT: "homePage_dialog_wechatExerciseAuthorization",
    EVENT_LOG_BUY: "commodityDetails_click_buy",
    EVENT_LOG_ACTIVITYSAVEPIC: "activity_click_savePictures",
    EVENT_LOG_BOXSHARE: "activity_share_openBox",
    EVENT_LOG_HOMEBUBBLE: "homePage_click_bubble",
    EVENT_LOG_HOMEADBUBBLE: "homePage_ball_Adbutton",
    EVENT_LOG_HOMESHARE: "homePage_share_buttonAndIconBtn",
    EVENT_LOG_HOMESHAREPLUS: "homePage_share_buttonAndIconPlus",
    EVENT_LOG_DIARYSAVEPIC: "diary_click_savesPictures",
    EVENT_LOG_HOMEPRODUCT: "homePage_click_product",
    EVENT_LOG_HOMEPRODUCT_SECOND: "homePage_click_product_second",
    EVENT_LOG_EXCHANGESTEP: "homePage_ball_exchangeStep",
    EVENT_LOG_HOMEMONEY: "homePage_click_money",
    EVENT_LOG_MINERULE: "mine_click_rule",
    EVENT_LOG_MINEFAQ: "mine_click_FAQ",
    EVENT_LOG_OPERATIONHOURS: "app_operation_hours",
    EVENT_APP_CLICKGAMEBOX: "app_click_gameBox",
    EVENT_APP_HOMEREWARDBUTTON: "homePage_rewardButton",
    EVENT_APP_REWARDLISTCLICK: "activeReward_clickAdvert",
    EVENT_LOG_ACTIVITY_CLICK_OPENBOX_SURE: "activity_click_openBox_sure",
    ENENT_LOG_ACTIVITY_OPENBOX: "activity_click_openBox",
    ENENT_LOG_APP_STEPCOUNT: "app_stepCount",
    ENENT_LOG_APP_THIRDPATRYPROGRAM: "app_thirdPatryProgram",
    ENENT_LOG_APP_OPENAPP: "app_openApp",
    ENENT_LOG_APP_CLICK_CHALLENGE: "app_click_challenge",
    ENENT_LOG_APP_CLICK_FRIENDCALL: "app_click_friendCall",
    ENENT_LOG_APP_ENTER_DIARY: "app_enter_diary",
    ENENT_LOG_DIARY_NEXTPIC: "diary_nextpic",
    ENENT_LOG_APP_ENTER_MINE: "app_enter_mine",
    ENENT_LOG_APP_ENTER_LUCKDRAWINFO: "app_enter_luckdrawinfo",
    ENENT_LOG_APP_LUCKDRAWINFO_SHARE: "app_luckdrawinfo_share",
    ENENT_LOG_APP_CLICK_CHALLENGESMALLCARD: "app_click_challengeSmallCard",
    EVENT_LOG_MINE_REMOND_APP: "mine_remond_app",
    EVENT_LOG_HOMEPAGE_CLICKREWARDBUTTON: "homepage_clickrewardbutton",
    EVENT_LOG_INDEX_ACTIVITY_CLCIK: "index_activity_clcik",
    EVENT_LOG_ADVERTLISTREWARDCLICK: "advertlistrewardclick",
    EVENT_LOG_ENTER_INDEX: "enter_index",
    EVENT_LOG_RAN_DETAILS: "index_ran_details",
    EVENT_LOG_INDEX_MORE_LIST: "index_more_list",
    EVENT_LOG_APP_CLICK_COOLECTION: "app_click_collection",
    EVENT_LOG_INDEX_STEPDETAILS: "index_setpdetails",
    EVENT_LOG_INDEX_MESSAGE: "index_message",
    EVENT_LOG_SUREJOIN: "app_click_surejoin_challenge",
    EVENT_LOG_INDEX_ENTER_ACTIVITY: "index_enter_activity",
    EVENT_LOG_CLICK_MORELINK: "index_click_morelink",
    EVENT_LOG_CLICK_FINDMORE: "index_click_findmore",
    EVENT_LOG_ENTER_INDEX_GOODDETAILS: "enter_index_gooddetails",
    EVENT_LOG_ENTER_INDEX_CLASSIFY: "enter_index_classify",
    EVENT_LOG_CLICK_GOODCOLLECT: "app_click_goodcollect",
    EVENT_LOG_ENTER_INDEX_COMMUNITY: "enter_index_community",
    EVENT_LOG_ENTER_COMMUNITY_TOPICS_CLICK: "enter_index_community_topics_click",
    EVENT_LOG_INVITE_COMMUNITY: "invite_community",
    EVENT_LOG_TOPICS_STAYTIME: "topics_staytime",
    EVENT_LOG_GOODDETAILSCLICK: "goodDetailsClick",
    EVENT_LOG_ACTIVITYREWARDSHARE: "activeRewardShare",
    EVENT_LOG_INDEXBANNER_INTO_COMMUNITY: "indexbanner_into_community",
    EVENT_LOG_COMMUNITYINFO_STAYTIME: "communityInfo_staytime",
    EVENT_LOG_HOMEPAGEACTIVITYSHARE: "homePage_activity_share",
    EVENT_LOG_ACTIVITYGOLDENPIGSHOW: "activity_golden_pig_show",
    EVENT_LOG_ACTIVITYGOLDENPIGSTAYTIME: "activity_golden_pig_stay_time",
    EVENT_LOG_ENTERINDEXGOODDETAILSCLICK: "enter_index_gooddetails_click",
    EVENT_LOG_HOMEPAGEACTIVITYCLICK: "homePage_activity_click",
    EVENT_CLICK_GOGAMEPAGE: "click_goGamePage",
    EVENT_GETINTO_GAME_USER_NUM: "getinto_game_user_num",
    EVENT_CLICK_GAME_USER_NUM: "click_game_user_num",
    EVENT_LEAVEGAME_USER_NUM: "leaveGame_user_num",
    EVENT_GAME_USER_YBCDJRS: "click_game_user_ybcdjrs",
    EVENT_GAME_USER_BGCS: "click_game_user_bgcs",
    EVENT_GAME_USER_YBCQXRS: "click_game_user_ybcqxrs",
    EVENT_GAME_USER_QXRS: "click_game_user_qxrs",
    EVENT_GANE_USER_YBCYXRS: "click_game_user_ybcyxrs",
    EVENT_GAME_USER_YXRS: "click_game_user_yxrs",
    EVENT_GAME_USER_DJRS: "click_game_user_djrs",
    EVENT_GAME_USER_YXTQXRS: "click_game_user_yxtqxrs",
    EVENT_LOG_COMMODITYDETAILS_EXCHANGE_NOTICE: "commodityDetails_exchange_notice",
    EVENT_SIGNIN_PAGE_CLICK: "signin_page_click",
    EVENT_SIGNIN_PAGE_CLICK_EXCHANGE: "signin_page_click_exchange",
    EVENT_SIGNIN_PAGE_CLICK_RESIGNIN: "signin_page_click_resignin"
};